version: '3.8'

services:
  # FastAPI Backend Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instabrief-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb+srv://akashpaul90766_db_user:7gZgXqm0VRqKXOmc@instabrief-cluster.cfzebhw.mongodb.net/?appName=instabrief-cluster
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET=your-jwt-secret-here
      - ENVIRONMENT=development
      - CORS_ORIGINS=*
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - instabrief-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: instabrief-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=instabrief
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - instabrief-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # LibreTranslate Service (Optional - for translation features)
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: instabrief-translate
    ports:
      - "5001:5000"
    environment:
      - LT_HOST=0.0.0.0
      - LT_CORS_ENABLED=true
      - LT_DISABLE_WEB_UI=false
      - LT_API_KEYS=false
    volumes:
      - libretranslate_models:/app/db
    networks:
      - instabrief-network
    restart: unless-stopped

volumes:
  mongo_data:
  libretranslate_models:


networks:
  instabrief-network:
    driver: bridge
